
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "nm2109m@gmail.com",
  "password": "Animated@1"
}

###
POST http://localhost:3000/refresh
headers: { 'Content-Type': 'application/json' }, 
