POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "nm2109m@gmail.com",
  "password": "Animated@1"
}

###
POST http://localhost:3000/log-out
Content-Type: application/json

###

POST http://localhost:3000/auth/refresh
headers: { 'Content-Type': 'application/json' } 
